name: Save and Restore

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v7

      - uses: actions/cache/restore@v6
        id: restore
        with:
          path: data/
          key: ${{ github.ref }}
          #fail-on-cache-miss: False


      - name: Pretend to add more data...
        run: |
          mkdir -p data
          date >> data/time.txt
          cat data/time.txt

      - uses: actions/cache/save@v6
        id: save
        with:
          path: data/
          key: ${{ github.ref }}

